app = "autonomind"

[build]
dockerfile = "docker/Dockerfile.cpu"

[env]
PORT = "8080"

[experimental]
auto_rollback = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 8000
    handlers = ["http"]
