app = "autonomind"

[build]
  dockerfile = "docker/Dockerfile.cpu"

[experimental]
  auto_rollback = true

# ─────────── FastAPI ──────────────
[[services]]
  internal_port = 8000
  protocol      = "tcp"

  # Expose it directly on 8000 to hit it from outside
  [[services.ports]]
    port     = 8000
    handlers = ["tls", "http"]

# ─────────── Next.js Frontend ─────
[[services]]
  internal_port = 3000
  protocol      = "tcp"

  # Expose Next.js at port 3000
  [[services.ports]]
    port     = 3000
    handlers = ["tls", "http"]
