app = "autonomind"

[build]
  dockerfile = "docker/Dockerfile.cpu"
  args = { MIN_CONFIDENCE = "0.4", NEXT_PUBLIC_FASTAPI_URL = "https://autonomind.fly.dev" }

[env]
  MIN_CONFIDENCE = "0.4"
  NEXT_PUBLIC_FASTAPI_URL = "https://autonomind.fly.dev"

[experimental]
  auto_rollback = true

# ─────────── FastAPI ──────────────
[[services]]
  internal_port = 8000
  protocol      = "tcp"

  # Expose it directly on 8000 to hit it from outside
  [[services.ports]]
    port     = 8000
    handlers = ["tls", "http"]

# ─────────── Next.js Frontend ─────
[[services]]
  internal_port = 3000
  protocol      = "tcp"

  # Map public HTTP(S) to the container's port 3000
  [[services.ports]]
    port     = 80
    handlers = ["http"]
  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

# Health checks
[[services.http_checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/api/ping"
  protocol = "http"
  tls_skip_verify = false
