app = "autonomind"

[build]
  dockerfile = "docker/Dockerfile.cpu"
  args = { NEXT_PUBLIC_FASTAPI_URL = "https://autonomind.fly.dev", MIN_CONFIDENCE = "0.4" }

[env]
  MIN_CONFIDENCE = "0.4"
  NEXT_PUBLIC_FASTAPI_URL = "https://autonomind.fly.dev"

[experimental]
  auto_rollback = true

# ─────────── FastAPI ──────────────
[[services]]
  internal_port = 8000
  protocol      = "tcp"

  # Expose it directly on 8000 to hit it from outside
  [[services.ports]]
    port     = 8000
    handlers = ["tls", "http"]

# ─────────── Next.js Frontend ─────
[[services]]
  internal_port = 3000
  protocol      = "tcp"

  # Map public HTTP(S) to the container's port 3000
  [[services.ports]]
    port     = 80
    handlers = ["http"]
  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]
