# --- docker/docker-compose.yml ---
version: '3.9'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.cpu
    ports:
      - "8080:8080"
      - "3000:3000"
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../:/app
    restart: always
